[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "survmetr"
version = "0.1.0"
description = "Advanced predictive metrics for survival analysis"
readme = "README.md"
requires-python = ">=3.11"
license = "LGPL-3.0-or-later"
authors = [{ name="Giovanni Birolo", email="giovanni.birolo@unito.it" }]
keywords = ["survival analysis", "concordance index", "antolini", "c-index", "time-dependent"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy>=2.0.2",
    "scikit-learn>=1.5.2",
    "scikit-survival>=0.23.1",
]

[project.optional-dependencies]
numba = ["numba"]

[project.urls]
Homepage = "https://github.com/compbiomed-unito/survival-metrics"
Repository = "https://github.com/compbiomed-unito/survival-metrics"
Issues = "https://github.com/compbiomed-unito/survival-metrics/issues"
